### ISSUE TITLE
Getting #75 to green

### ISSUE THREAD

**Issue by johnnyshields** [gmailgem/gmail#107]
_From @webcracy on April 23, 2014 10:28_

I found that without merging `master` into this branch was causing many errors and that we needed to add `rdoc` as a development dependency to even run with 1.8.7. 

After upgrading `rspec` and `mocha` as well, I only have a single failure with 1.8.7 -- all green on 1.9.2-p320 and 1.9.3-p545.

### Ruby 1.8.7-p374

```
Failures:

  1) Gmail client (Plain) instance should deliver inline composed email
     Failure/Error: client.deliver do
       expected: true value
            got: false
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-expectations-2.14.5/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-expectations-2.14.5/lib/rspec/expectations/handler.rb:36:in `handle_matcher'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-expectations-2.14.5/lib/rspec/expectations/syntax.rb:53:in `should'
     # ./spec/client_spec.rb:104
     # ./spec/client_spec.rb:25:in `mock_client'
     # ./spec/client_spec.rb:103
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:114:in `instance_eval'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:114:in `run'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:111:in `run'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:390:in `run_examples'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:386:in `map'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:386:in `run_examples'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:371:in `run'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `run'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `map'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `run'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `run'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `run'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:58:in `report'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `autorun'
     # /Users/alex/.rvm/gems/ruby-1.8.7-p374/bin/rspec:23

Finished in 25.97 seconds
43 examples, 1 failure, 12 pending

Failed examples:

rspec ./spec/client_spec.rb:102 # Gmail client (Plain) instance should deliver inline composed email
/Users/alex/.rvm/rubies/ruby-1.8.7-p374/bin/ruby -S rspec ./spec/client_spec.rb ./spec/gmail_spec.rb ./spec/mailbox_spec.rb ./spec/message_spec.rb failed
```

_Copied from original issue: nu7hatch/gmail/pull/107_

**Comment by johnnyshields** [comment]
_From @jgrevich on April 25, 2014 21:31_

I'm still getting the same 4 tests failing as in #75 in both 1.8.7 and 1.9.3. 
```
Failed examples:

rspec ./spec/client_spec.rb:93 # Gmail client (Plain) instance #compose should automatically add `from` header when it is not specified
rspec ./spec/client_spec.rb:102 # Gmail client (Plain) instance should deliver inline composed email
rspec ./spec/mailbox_spec.rb:24 # A Gmail mailbox instance should be able to count all emails
rspec ./spec/mailbox_spec.rb:30 # A Gmail mailbox instance should be able to find messages
```

I'm using Ruby 1.9.3-p545 with the following gems:

```
bigdecimal (1.1.0)
bundler (1.6.1)
bundler-unload (1.0.2)
diff-lcs (1.2.5)
executable-hooks (1.3.1)
gem-wrappers (1.2.4)
gmail_xoauth (0.4.1)
hoe (3.12.0)
io-console (0.3)
json (1.5.5)
mail (2.5.4)
metaclass (0.0.4)
mime (0.4.1)
mime-types (1.25.1)
minitest (2.5.1, 1.7.2)
mocha (1.0.0, 0.11.0)
oauth (0.4.7)
polyglot (0.3.4)
rake (10.3.1, 0.9.2.2)
rdoc (3.9.5, 2.4.3)
rspec (2.14.1)
rspec-core (2.14.8)
rspec-expectations (2.14.5)
rspec-mocks (2.14.6)
rubygems-bundler (1.4.3)
rvm (1.11.3.9)
treetop (1.4.15)
```

Let me see if I can figure out more about why these other tests are failing on my side.
