### ISSUE TITLE
calling 'message' on email object returns 'wrong number of arguments (1 for 0 )

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#125]
_From @shawnbro on December 11, 2014 15:44_

Any idea why?

Here is the block:

`gmail.inbox.emails(:unread, from: sent_email.to_email).each do |inbox_email|
       puts "INBOX EMAIL: #{inbox_email.message}"
  end`

which throws this error:

ArgumentError: wrong number of arguments (1 for 0)
	from /Users/.../.rvm/gems/ruby-2.1.2/gems/gmail-0.4.2/lib/gmail/client/imap_extensions.rb:7:in `msg_att'
	from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:2210:in `numeric_response'
	from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:2152:in `response_untagged'
	from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:2132:in `response'
	from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:2058:in `parse'
	from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:1181:in `get_response'
	from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:1089:in `receive_responses'
	from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:1075:in `block in initialize'

_Copied from original issue: nu7hatch/gmail#125_

**Comment by bootstraponline** [comment]
_From @shawnbro on December 11, 2014 15:54_

This Pull request fixes the issue:

https://github.com/nu7hatch/gmail/pull/122/files
