### ISSUE TITLE
Cannot interact with messages.

### ISSUE THREAD

**Issue by jaredpohl** [gmailgem/gmail#158]
Guys - 

I get the following error when I use the following code.  I can log in and count messages etc, but when I try to interact with messages i get the following error:  

Code:
```
require 'Gmail'
gmail = Gmail.connect(uname,pword)

gmail.inbox.find(:all).each do |mail|
	puts mail.message
end
```

Error:

```
/Users/jaredpohl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/gmail-0.4.2/lib/gmail/client/imap_extensions.rb:7:in `msg_att': wrong number of arguments (1 for 0) (ArgumentError)
	from /Users/jaredpohl/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/imap.rb:2210:in `numeric_response'
	from /Users/jaredpohl/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/imap.rb:2152:in `response_untagged'
	from /Users/jaredpohl/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/imap.rb:2132:in `response'
	from /Users/jaredpohl/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/imap.rb:2058:in `parse'
	from /Users/jaredpohl/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/imap.rb:1181:in `get_response'
	from /Users/jaredpohl/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/imap.rb:1089:in `receive_responses'
	from /Users/jaredpohl/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/imap.rb:1075:in `block in initialize'
```

I just want to log in, find some emails, get the attachments, and then delete.  

Thanks for the help guys.

**Comment by jaredpohl** [comment]
found another issue which covered off on this.. apologies
