### ISSUE TITLE
Thread-safety issues

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#34]
_From @nu7hatch on August 17, 2011 18:45_

Need to figure out how to provide thread safety for this gem... (mentioned here https://github.com/nu7hatch/gmail/pull/28)

_Copied from original issue: nu7hatch/gmail#34_

**Comment by bootstraponline** [comment]
_From @XULRunner42 on February 14, 2012 20:41_

I can confirm that I still get this error when trying to download attachments from a label, as described in the README

    <internal:prelude>:8:in `lock': deadlock; recursive locking (ThreadError)
	from <internal:prelude>:8:in `synchronize'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `mailbox'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/message.rb:157:in `message'
	from ./mail-outbocks.rb:23:in `block in <main>'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:65:in `call'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:65:in `block (2 levels) in emails'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:63:in `collect'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:63:in `block in emails'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/client/base.rb:161:in `call'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/client/base.rb:161:in `block in mailbox'
	from <internal:prelude>:10:in `synchronize'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `mailbox'
	from /home/yebyen/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:62:in `emails'
	from ./mail-outbocks.rb:21:in `<main>'

**Comment by bootstraponline** [comment]
_From @XULRunner42 on February 14, 2012 21:55_

with ruby 1.8.7 it's a different error, i am just using bundle now because it seems the gem can't be found otherwise.

the gem it seems is mostly functional, until it comes to retrieving large groups of e-mails...

    in `synchronize': thread 0x284431a8 tried to join itself (ThreadError)

    /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `synchronize': thread 0x284431a8 tried to join itself (ThreadError)
	    from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `mailbox'
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/message.rb:157:in `message'
    	from ./mail-outbocks.rb:23
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/mailbox.rb:65:in `call'
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/mailbox.rb:65:in `emails'
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/mailbox.rb:63:in `collect'
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/mailbox.rb:63:in `emails'
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/client/base.rb:161:in `call'
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/client/base.rb:161:in `mailbox'
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `synchronize'
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `mailbox'
    	from /usr/local/lib/ruby/gems/1.8/gems/gmail-0.4.0/lib/gmail/mailbox.rb:62:in `emails'
    	from ./mail-outbocks.rb:21

**Comment by bootstraponline** [comment]
_From @XULRunner42 on February 14, 2012 21:56_

I suppose I should include line 21... 

    gmail.label("outbocks").emails do |email|

      if !email.message.attachments.empty?
        count+=1
        puts "hello attachment #{count}"
      #  email.message.save_attachments_to(folder)
      end
    end

Line 21 is the first line I've posted.  It never runs the code block passed, even once.

**Comment by bootstraponline** [comment]
_From @TylerBrock on April 10, 2012 17:18_

Any updates on this issue, seems as though it is still broken.

**Comment by bootstraponline** [comment]
_From @XULRunner42 on April 10, 2012 17:46_

Not on my end... I wound up with gmail_attachment_downloader based on tmail, which is Ruby 1.8.7 only (last time I checked).  I saw tmail gem deployed somewhere in my org where 1.9.3 is being used now, but I'm not sure it's live.

**Comment by bootstraponline** [comment]
_From @jamesladd on April 17, 2012 23:28_

This is holding me up too.

ThreadError: thread 0x1ce2268 tried to join itself
	from /home/jamesl/.rvm/gems/ree-1.8.7-2011.03@megastore/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `synchronize'
	from /home/jamesl/.rvm/gems/ree-1.8.7-2011.03@megastore/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `mailbox'
	from /home/jamesl/.rvm/gems/ree-1.8.7-2011.03@megastore/gems/gmail-0.4.0/lib/gmail/message.rb:157:in `message'

**Comment by bootstraponline** [comment]
_From @tonyarkles on April 27, 2012 4:0_

I just got burned on this too:

```
1.9.3p0 :003 > gmail.inbox.find(:unread) do |em| puts em end
ThreadError: deadlock; recursive locking
	from <internal:prelude>:8:in `lock'
	from <internal:prelude>:8:in `synchronize'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `mailbox'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/message.rb:151:in `envelope'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/message.rb:131:in `method_missing'
	from (irb):3:in `puts'
	from (irb):3:in `puts'
	from (irb):3:in `block in irb_binding'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:65:in `call'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:65:in `block (2 levels) in emails'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:63:in `collect'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:63:in `block in emails'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/client/base.rb:161:in `call'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/client/base.rb:161:in `block in mailbox'
	from <internal:prelude>:10:in `synchronize'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `mailbox'
	from /Users/aja042/.rvm/gems/ruby-1.9.3-p0/gems/gmail-0.4.0/lib/gmail/mailbox.rb:62:in `emails'
	from (irb):3
```

I just forked and will try to have a look at this in more detail in the morning.

**Comment by bootstraponline** [comment]
_From @jtprince on August 28, 2012 19:1_

still getting this error on gem downloaded today:

```
<internal:prelude>:8:in `lock': deadlock; recursive locking (ThreadError)
	from <internal:prelude>:8:in `synchronize'
	from /home/jtprince/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/gmail-0.4.0/lib/gmail/client/base.rb:154:in `mailbox'
...
```

**Comment by bootstraponline** [comment]
_From @tredger on September 19, 2012 11:36_

@tonyarkles This is because you are missing the .each (this is also missing from the code examples in the readme issue for this can be found here: https://github.com/nu7hatch/gmail/pull/65). Instead use 
<pre>
gmail.inbox.find(:unread).each do |em| puts em end
</pre>

**Comment by bootstraponline** [comment]
_From @tonyarkles on September 19, 2012 13:42_

@tredger Thanks! I'll give that a shot this afternoon and see. The project I was working on kind of got put on the shelf, but this seems like a good reason to revisit it!

**Comment by bootstraponline** [comment]
_From @mjfreshyfresh on September 23, 2012 11:41_

@tredger You're correct, include the "EACH" in that statement and it works. Thanks!

**Comment by bootstraponline** [comment]
_From @johnnyshields on January 15, 2015 14:18_

Closing this issue as it's 3 years old and no recent activity. Please file a separate it issue if there are any follow-ups.
