### ISSUE TITLE
Crash when fetching an envelope in Ruby 2

### ISSUE THREAD

**Issue by johnnyshields** [gmailgem/gmail#97]
_From @orfattal on December 29, 2013 8:51_

After upgrading to ruby-2.0.0-p353 from 1.9.3, fetching an envelope crashes. here's the stack when calling `envelope` from rails console:
```
2.0.0p353 :007 > emails.first.envelope
ArgumentError: wrong number of arguments (1 for 0)
	from /Users/orfattal/.rvm/gems/ruby-2.0.0-p353@silo/bundler/gems/gmail-3bb194543c0f/lib/gmail/client/imap_extensions.rb:5:in `msg_att'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:2210:in `numeric_response'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:2152:in `response_untagged'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:2132:in `response'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:2058:in `parse'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:1181:in `get_response'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:1089:in `receive_responses'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:1075:in `block in initialize'
```

_Copied from original issue: nu7hatch/gmail#97_

**Comment by johnnyshields** [comment]
_From @raravena-coupa on November 6, 2014 23:45_

Seeing the same problem here.

**Comment by johnnyshields** [comment]
_From @jimlindstrom on November 22, 2014 2:51_

Looks like [gmail/lib/gmail/client/imap_extensions.rb:7](https://github.com/nu7hatch/gmail/blob/master/lib/gmail/client/imap_extensions.rb#L7) needs to change from

    def msg_att

to

    def msg_att(n)

See: http://yard.ruby-doc.org/stdlib-2.1.2/Net/IMAP/ResponseParser.html#msg_att-instance_method

**Comment by johnnyshields** [comment]
_From @bootstraponline on December 3, 2014 19:55_

I just encountered the same problem. This gem seems to be abandonware? I'm using it and need the fixes on rubygems so I had to fork.

**Comment by johnnyshields** [comment]
_From @weshatheleopard on December 3, 2014 20:17_

Doesn't seem like abandonware, last commit 14 days ago.

**Comment by johnnyshields** [comment]
_From @bootstraponline on December 3, 2014 20:20_

Ok. Hopefully the maintainers accept your [pull request](https://github.com/nu7hatch/gmail/pull/122).

**Comment by johnnyshields** [comment]
@bootstraponline @weshatheleopard It's not abandonware, the original maintainer (nu7hatch) has transitioned the ownership to a new group of maintainers. I hope to spend time merging PRs over the holiday season.

**Comment by johnnyshields** [comment]
This is now fixed on master.
